services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 shopy.wsgi:application
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=shopy.settings.prod
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
      build: .
      command: celery -A shopy worker -l info -P eventlet
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      depends_on:
        - redis
        - rabbitmq
      volumes:
        - .:/app

  stripe:
    image: stripe/stripe-cli
    command: listen --forward-to web:8001/payment/webhook/
    depends_on:
      - web
