# Generated by Django 4.1.13 on 2025-03-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
