# Generated by Django 4.1.13 on 2025-03-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
