# Generated by Django 4.1.13 on 2025-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_collection_product_collection_collectiontranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontranslation',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
