# Generated by Django 4.1.13 on 2025-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_collectiontranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontranslation',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
